<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StepGo.Marketing.Client\StepGo.Marketing.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\libs\StepGo.UI\StepGo.UI.csproj" />
    <ProjectReference Include="..\..\..\libs\StepGo.ApiClient\StepGo.ApiClient.csproj" />
    <ProjectReference Include="..\..\..\libs\StepGo.PricingRules\StepGo.PricingRules.csproj" />
  </ItemGroup>

</Project>
